from . import model_a
from . import model_f
from . import property 
from . import owner 
from . import tag
from . import client
from . import sale_order
from . import res_partner
from . import building